# Generated by Django 3.2.15 on 2024-02-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('salary', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salaries',
                'db_table': 'salaries',
            },
        ),
    ]
